# -*- coding: utf-8 -*-
"""break_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B29oZ1jl6sPe5ZG9ilUoRnzhQYFmfFP7
"""

import glob
import os
import zipfile
import pandas as pd

zip_path = "/content/data_Q1_2026.zip"
extract_dir = "/content/extracted_data"

if not os.path.exists(extract_dir):
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(extract_dir)

all_files = glob.glob(os.path.join(extract_dir, "**/*.csv"), recursive=True)

print("Loding Data")

try:
    df_list = [pd.read_csv(f) for f in all_files]
    full_df = pd.concat(df_list)
    print("Success - Full dataset loaded without errors!")

except MemoryError:
    print("Ran out of memory while loading data!")